<?php

App::uses('AppModel', 'Model');

class RecruitingDatum extends AppModel {
    public $defaultFields = array(
        'RecruitingDatum.id',
        'RecruitingDatum.hospital_data_id',
        'RecruitingDatum.qualification_id',
        'RecruitingDatum.working_style_id',
        'RecruitingDatum.haizoku_id',
        'RecruitingDatum.pref_cd',
        'RecruitingDatum.ward_cd',
        'RecruitingDatum.address',
        'RecruitingDatum.recruitment_process',
        'RecruitingDatum.required_experience',
        'RecruitingDatum.yearly_salary_max',
        'RecruitingDatum.monthly_salary_max',
        'RecruitingDatum.hourly_salary_max',
        'RecruitingDatum.yearly_salary_min',
        'RecruitingDatum.monthly_salary_min',
        'RecruitingDatum.hourly_salary_min',
        'RecruitingDatum.bounus',
        'RecruitingDatum.night_shift_salary',
        'RecruitingDatum.other_benefits',
        'RecruitingDatum.transportation_costs_id',
        'RecruitingDatum.shift_system_id',
        'RecruitingDatum.average_overtime',
        'RecruitingDatum.average_duty_count',
        'RecruitingDatum.yearly_holiday',
        'RecruitingDatum.paid_vacation',
        'RecruitingDatum.holiday_id',
        'RecruitingDatum.welfare',
        'RecruitingDatum.car_commuting_id',
        'RecruitingDatum.nursery_flag',
        'RecruitingDatum.nursery_limit',
        'RecruitingDatum.nursery_price',
        'RecruitingDatum.dormitory_flag',
        'RecruitingDatum.dormitory_floor',
        'RecruitingDatum.dormitory_price',
        'RecruitingDatum.business_id',
        'RecruitingDatum.recruitment_start_date',
        'RecruitingDatum.recruitment_end_date',
        'RecruitingDatum.insert_date',
		'RecruitingDatum.update_date',
		'RecruitingDatum.order_rank_id',
		'RecruitingDatum.proagent_id',
		'RecruitingDatum.transportation_costs',
		'RecruitingDatum.address_free',
        'RecruitingDatum.parking_fee',
        'RecruitingDatum.working_style_memo',
        'RecruitingDatum.history_business_id',
        'RecruitingDatum.history_status',
        'RecruitingDatum.history_date',
        'RecruitingDatum.bounus_memo',
        'RecruitingDatum.assumed_salary',
        'RecruitingDatum.age_average',
        'RecruitingDatum.age_limit',
        'RecruitingDatum.business_content',
        'RecruitingDatum.salary_model',
        'RecruitingDatum.from_year_salary',
        'RecruitingDatum.to_year_salary',
        'RecruitingDatum.gainful_holiday_digestion_rate',
        'RecruitingDatum.dormitory_info',
        'RecruitingDatum.private_car_flag',
        'RecruitingDatum.private_car_info',
        'RecruitingDatum.leave_childbirth_flag',
        'RecruitingDatum.leave_childbirth_info',
        'RecruitingDatum.accept_count',
        'RecruitingDatum.education_system',
        'RecruitingDatum.nurse_count',
        'RecruitingDatum.nurse_age_bracket',
        'RecruitingDatum.nurse_quinquennial',
        'RecruitingDatum.age_retirement',
        'RecruitingDatum.copy_id',
        'RecruitingDatum.night_working_hours',
        'RecruitingDatum.holiday_for_years',
        'RecruitingDatum.baby_farm_flag',
        'RecruitingDatum.baby_farm_info',
        'RecruitingDatum.nurse_average',
        'RecruitingDatum.from_age_limit',
        'RecruitingDatum.to_age_limit',
        'RecruitingDatum.tag_blank_ok',
        'RecruitingDatum.tag_return_to_work_support',
        'RecruitingDatum.tag_mother_job_well_tag',
        'RecruitingDatum.tag_freshman_recruit_ok',
        'RecruitingDatum.tag_place_of_work',
        'RecruitingDatum.tag_rental_uniform',
        'RecruitingDatum.tag_unexperience',
        'RecruitingDatum.tag_mather_welcome',
        'RecruitingDatum.tag_male_welcome',
        'RecruitingDatum.tag_high_salary',
        'RecruitingDatum.daily_salary_min',
        'RecruitingDatum.daily_salary_max',
        'RecruitingDatum.house_benefits_flag',
        'RecruitingDatum.house_benefits',
        'RecruitingDatum.night_working_flag',
        'RecruitingDatum.night_working',
        'RecruitingDatum.holiday_etc',
        'RecruitingDatum.tag_holiday',
        'RecruitingDatum.selectable_insurance',
        'RecruitingDatum.car_park_flag',
        'RecruitingDatum.tag_education_system',
        'RecruitingDatum.institutional_retire_flag',
        'RecruitingDatum.institutional_retire_info',
        'RecruitingDatum.dummy_flag',
        'RecruitingDatum.posting_flag',
        'RecruitingDatum.pickup_flag',
        'RecruitingDatum.tag_near_station',
        'RecruitingDatum.accept_flag',
        'RecruitingDatum.bounus_count',
        'RecruitingDatum.bounus_month',
        'RecruitingDatum.search_monthly_salary_min',
        'RecruitingDatum.already_posting_flag',
        'RecruitingDatum.night_shift_info',
        'RecruitingDatum.holiday_info',
        'RecruitingDatum.welfare_info',
        'RecruitingDatum.salary_memo',
        'RecruitingDatum.finally_updated_business_id',
        'RecruitingDatum.confirm_flag',
        'RecruitingDatum.base_salary_min',
        'RecruitingDatum.base_salary_max',
    );
   
    /**
     * Validation rules
     *
     * @var array
     */
    public $validate = array(
        'hospital_data_id' => array(
            'notempty' => array(
                'rule' => array('notempty'),
                'message' => 'This field could not be empty',
            ),
        ),
    );
  

}
